import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:innolearn_innoviast/screens/auth/auth_service.dart';
import 'package:innolearn_innoviast/screens/auth/firestore_service.dart';
import 'package:innolearn_innoviast/screens/home/welcome_screen.dart';
import 'package:innolearn_innoviast/services/progress_service.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart'; // auto-generated by `flutterfire configure`
import 'theme/app_theme.dart';

import 'screens/main_navigation.dart'; // your existing home shell after login

Future<void> main() async {
  // Required before calling any Firebase function
  WidgetsFlutterBinding.ensureInitialized();

  // Connects the app to your Firebase project using firebase_options.dart
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const InnoLearnApp());
}

class InnoLearnApp extends StatelessWidget {
  const InnoLearnApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Makes AuthService available everywhere in the widget tree
        ChangeNotifierProvider(create: (_) => AuthService()),
        Provider(create: (_) => FirestoreService()),
        ChangeNotifierProvider(create: (_) => ProgressService()),
      ],
      child: MaterialApp(
        title: 'InnoLearn',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light,
        home: const AuthGate(),
      ),
    );
  }
}

/// Decides whether to show Login screen or Home screen
/// based on whether a user is currently signed in.
class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = context.watch<AuthService>();

    return StreamBuilder(
      stream: authService.authStateChanges,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }
        if (snapshot.hasData) {
          // User is logged in
          return const MainNavigation();
        }
        // No user -> show welcome/login entry screen
        return const WelcomeScreen();
      },
    );
  }
}